apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  labels:
    app: msa-banking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auth-service
      app: msa-banking-app

  template:
    metadata:
      name: auth-msa-pod
      labels:
        name: auth-service
        app: msa-banking-app
    spec:
      containers:
      - name: auth-container
        image: ${REPOSITORY_TAG}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 700m
            memory: 700Mi

      imagePullSecrets:
          - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  labels:
    name: auth-service
    app: msa-banking-app

spec:
  type: ClusterIP
  ports:
  -  protocol: TCP
     targetPort: 9080
     port: 9080

  selector:
    name: auth-service
    app: msa-banking-app
